### ISSUE TITLE
Тексты и описание

### ISSUE THREAD

**Issue by nevmenandr** [phuuda/Old-High-German#1]
Мне кажется, удобнее положить все тексты с .txt на конце в одну папку, а .csv с их описанием в ту же папку не класть. Вынести это описание куда-то на уровень выше. Тогда сможем просто задать обработку всех файлов в директории через os.listdir(), не обращая внимания на то, что это за файл.

**Comment by phuuda** [comment]
Хорошо, я перенесла тексты .txt в одну папку.
